// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haadmoehrfjvrkfiojnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhYWRtb2VocmZqdnJrZmlvam5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNDA2NTMsImV4cCI6MjA1OTgxNjY1M30.Z48qEf9Tg4PlZgvyNVzbA7gGaLQir7O7fmkRRz6JMi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);